# -*- coding: utf-8 -*-
"""Bot_ST2DYTechQnA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XgjU664lihz3NbNcfab8yPvz9HnZGrqd
"""

!pip install chatterbot

!pip install chatterbot-corpus

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import logging
logging.basicConfig(filename='archivador.log',level=logging.DEBUG)

bot = ChatBot('ST2DY_Tech',
              storage_adapter='chatterbot.storage.SQLStorageAdapter',
              database_uri='sqlite:///database.sqlite3'
)

entrenador = ListTrainer(chatbot)

entrenador.train([
    'Hola',
    'Hola ¿Puedo ayudarte en algo?',
    '¿Como estas?',
    'Bien, bien y tu?',
    'Bien',
    'Que bueno'
])

entrenador.train([
    '¿Hola, como estas?',
    'Hola!! Excelente ¿y tu?',
    'Bien, gracias',
    '¡Genial!'
    
])

entrenador.train([
    '¿Cual es tu funcion?',
    'Soy ST2DY_Tech. Un Bot creado para responder tus dudas acerca de ST2DYTech.',
    '¿¿Què es ST2DYTech??',
    'ST2DYTech es una herramienta digital creada para ayudar a los estudiantes a mejorar su nivel academico y generar un gusto por la tecnologia y la innvoacion.',
    '¿Quienes pueden usar ST2DYTech?',
    'Pueden usarlo desde niños de primaria hasta estudiantes de universidad.'
])

entrenador.train([
    '¿Que contiene ST2DYTech',
    'ST2DYTech se compone de simuladores virtuales para mejorar el aprendizaje de los estudiantes, ademàs de clases y ejercicios',
    '¿Tiene algun enfoque especial?',
    'Sì, està enfocado principalmente a niños de primaria, por ende se impartiran conocimientos basicos pero solidos.',
    'Ok, muchas gracias',
    'Con gusto, pera servirte.'
    
])

entrenador.train([
    '¿Què tendrà a futuro?',
    'A futuro se le implementarà màs contenido, firmas y tutores entre otras cosas, ademas de enlaces con los maestros para poder ser utilizado a la par de los cursos escolares.',
    '¿Còmo lo puedo usar?',
    'Puedes seguir estos pasos, 1) Ingresar a la plataforma y dar click en registrarme. 2) Ingresar los datos del formulario de registro. 3) Una vez ya ingresaro, podras deleccionar la materia que quisieras visualizar. 4) Selecciona un tema a visualizar. 5)Visualiza el tema, el video y el ejercicio de apoyo. 6) Cuando finalices el tema correctamente adquiriras experiencia en la plataforma lo que te dara medallas.'
    
])

while True:
  try:
    bot_input = bot.get_response(input())
    print(bot_input)

  except(KeyboardInterrupt, EOFError, SystemExit):
    break